// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminalFrameDiff {
    #[prost(string, tag = "1")]
    pub frame_schema_version: ::prost::alloc::string::String,
    #[prost(enumeration = "TerminalFrameKind", tag = "2")]
    pub frame_kind: i32,
    #[prost(message, repeated, tag = "3")]
    pub rows: ::prost::alloc::vec::Vec<TerminalRow>,
    #[prost(message, optional, tag = "4")]
    pub cursor: ::core::option::Option<TerminalCursor>,
    #[prost(message, optional, tag = "5")]
    pub selection: ::core::option::Option<TerminalSelection>,
    #[prost(uint32, tag = "6")]
    pub viewport_rows: u32,
    #[prost(uint32, tag = "7")]
    pub viewport_cols: u32,
    #[prost(message, repeated, tag = "8")]
    pub dirty_ranges: ::prost::alloc::vec::Vec<TerminalDirtyRange>,
    #[prost(uint32, tag = "9")]
    pub scrollback_offset: u32,
    #[prost(uint32, tag = "10")]
    pub scrollback_max_offset: u32,
    #[prost(uint32, tag = "11")]
    pub viewport_start_row: u32,
    #[prost(int32, tag = "12")]
    pub viewport_row_shift: i32,
    #[prost(message, optional, tag = "13")]
    pub default_foreground: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "14")]
    pub default_background: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "15")]
    pub cursor_color: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "16")]
    pub modes: ::core::option::Option<TerminalFrameModes>,
    #[prost(string, tag = "17")]
    pub window_title: ::prost::alloc::string::String,
    #[prost(string, tag = "18")]
    pub window_icon_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "19")]
    pub hyperlinks: ::prost::alloc::vec::Vec<TerminalHyperlinkRange>,
    #[prost(message, repeated, tag = "20")]
    pub inline_images: ::prost::alloc::vec::Vec<TerminalInlineImage>,
    #[prost(message, repeated, tag = "21")]
    pub graphics: ::prost::alloc::vec::Vec<TerminalGraphicPlacement>,
    #[prost(uint64, optional, tag = "22")]
    pub global_bottom_row: ::core::option::Option<u64>,
    #[prost(string, tag = "23")]
    pub pointer_shape: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "24")]
    pub sized_text: ::prost::alloc::vec::Vec<TerminalSizedTextPlacement>,
    #[prost(message, optional, tag = "25")]
    pub selection_background: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "26")]
    pub selection_foreground: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "27")]
    pub link_color: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "28")]
    pub cursor_text_color: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "29")]
    pub tab_color: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "30")]
    pub cursor_guide_color: ::core::option::Option<ColorRgb>,
    #[prost(message, repeated, tag = "31")]
    pub blocks: ::prost::alloc::vec::Vec<TerminalBlock>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminalRow {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub wrapped: bool,
    #[prost(int64, tag = "4")]
    pub modified_at_micros: i64,
    #[prost(message, repeated, tag = "5")]
    pub style_runs: ::prost::alloc::vec::Vec<TerminalStyleRun>,
    #[prost(uint32, optional, tag = "6")]
    pub source_row: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub source_end_row: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalBlock {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub block_type: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub start_row: u32,
    #[prost(uint32, tag = "4")]
    pub end_row: u32,
    #[prost(uint32, tag = "5")]
    pub source_start_row: u32,
    #[prost(uint32, tag = "6")]
    pub source_end_row: u32,
    #[prost(bool, tag = "7")]
    pub folded: bool,
    #[prost(uint32, tag = "8")]
    pub hidden_rows: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalStyleRun {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, tag = "2")]
    pub end: u32,
    #[prost(message, optional, tag = "3")]
    pub foreground: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "4")]
    pub background: ::core::option::Option<ColorRgb>,
    #[prost(bool, tag = "5")]
    pub bold: bool,
    #[prost(bool, tag = "6")]
    pub dim: bool,
    #[prost(bool, tag = "7")]
    pub italic: bool,
    #[prost(bool, tag = "8")]
    pub underline: bool,
    #[prost(bool, tag = "9")]
    pub blink: bool,
    #[prost(bool, tag = "10")]
    pub inverse: bool,
    #[prost(message, optional, tag = "11")]
    pub underline_color: ::core::option::Option<ColorRgb>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ColorRgb {
    #[prost(bool, tag = "1")]
    pub present: bool,
    #[prost(uint32, tag = "2")]
    pub rgb: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalCursor {
    #[prost(uint32, tag = "1")]
    pub row: u32,
    #[prost(uint32, tag = "2")]
    pub col: u32,
    #[prost(bool, tag = "3")]
    pub visible: bool,
    #[prost(string, optional, tag = "4")]
    pub shape: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "5")]
    pub blink: ::core::option::Option<bool>,
    #[prost(bool, tag = "6")]
    pub highlight_line: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalSelection {
    #[prost(bool, tag = "1")]
    pub present: bool,
    #[prost(uint32, tag = "2")]
    pub start_row: u32,
    #[prost(uint32, tag = "3")]
    pub start_col: u32,
    #[prost(uint32, tag = "4")]
    pub end_row: u32,
    #[prost(uint32, tag = "5")]
    pub end_col: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalDirtyRange {
    #[prost(uint32, tag = "1")]
    pub start: u32,
    #[prost(uint32, tag = "2")]
    pub end: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalFrameModes {
    #[prost(bool, tag = "1")]
    pub alternate_screen: bool,
    #[prost(bool, tag = "2")]
    pub alternate_scroll: bool,
    #[prost(bool, tag = "3")]
    pub application_cursor: bool,
    #[prost(bool, tag = "4")]
    pub application_keypad: bool,
    #[prost(bool, tag = "5")]
    pub insert_mode: bool,
    #[prost(bool, tag = "6")]
    pub origin_mode: bool,
    #[prost(bool, tag = "7")]
    pub line_feed_new_line_mode: bool,
    #[prost(bool, tag = "8")]
    pub hide_cursor: bool,
    #[prost(bool, tag = "9")]
    pub bracketed_paste: bool,
    #[prost(bool, tag = "10")]
    pub focus_tracking: bool,
    #[prost(bool, tag = "11")]
    pub char_protected: bool,
    #[prost(string, tag = "12")]
    pub mouse_mode: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub mouse_encoding: ::prost::alloc::string::String,
    #[prost(uint32, tag = "14")]
    pub kitty_keyboard_flags: u32,
    #[prost(bool, tag = "15")]
    pub synchronized_output: bool,
    #[prost(bool, tag = "16")]
    pub mime_paste: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalHyperlinkRange {
    #[prost(uint32, tag = "1")]
    pub row: u32,
    #[prost(uint32, tag = "2")]
    pub start_col: u32,
    #[prost(uint32, tag = "3")]
    pub end_col: u32,
    #[prost(string, tag = "4")]
    pub uri: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub protocol_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalSizedTextPlacement {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub row: u32,
    #[prost(uint32, tag = "3")]
    pub col: u32,
    #[prost(uint32, tag = "4")]
    pub width_cells: u32,
    #[prost(uint32, tag = "5")]
    pub height_cells: u32,
    #[prost(uint32, tag = "6")]
    pub source_row_offset_cells: u32,
    #[prost(uint32, tag = "7")]
    pub visible_height_cells: u32,
    #[prost(uint32, tag = "8")]
    pub scale: u32,
    #[prost(uint32, tag = "9")]
    pub subscale_n: u32,
    #[prost(uint32, tag = "10")]
    pub subscale_d: u32,
    #[prost(uint32, tag = "11")]
    pub vertical_align: u32,
    #[prost(uint32, tag = "12")]
    pub horizontal_align: u32,
    #[prost(bool, tag = "13")]
    pub natural_width: bool,
    #[prost(message, optional, tag = "14")]
    pub foreground: ::core::option::Option<ColorRgb>,
    #[prost(message, optional, tag = "15")]
    pub background: ::core::option::Option<ColorRgb>,
    #[prost(bool, tag = "16")]
    pub bold: bool,
    #[prost(bool, tag = "17")]
    pub dim: bool,
    #[prost(bool, tag = "18")]
    pub italic: bool,
    #[prost(bool, tag = "19")]
    pub underline: bool,
    #[prost(bool, tag = "20")]
    pub blink: bool,
    #[prost(bool, tag = "21")]
    pub inverse: bool,
    #[prost(message, optional, tag = "22")]
    pub underline_color: ::core::option::Option<ColorRgb>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalInlineImage {
    #[prost(string, tag = "1")]
    pub data: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub row: u32,
    #[prost(uint32, tag = "4")]
    pub col: u32,
    #[prost(uint32, tag = "5")]
    pub width_cells: u32,
    #[prost(uint32, tag = "6")]
    pub height_cells: u32,
    #[prost(string, tag = "7")]
    pub alt_text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalGraphicAssetKey {
    #[prost(uint64, tag = "1")]
    pub asset_id: u64,
    #[prost(uint64, tag = "2")]
    pub asset_version: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TerminalGraphicPlacement {
    #[prost(uint64, tag = "1")]
    pub placement_id: u64,
    #[prost(uint64, tag = "2")]
    pub render_id: u64,
    #[prost(message, optional, tag = "3")]
    pub asset_key: ::core::option::Option<TerminalGraphicAssetKey>,
    #[prost(string, tag = "4")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub row: u32,
    #[prost(uint32, tag = "6")]
    pub col: u32,
    #[prost(uint32, tag = "7")]
    pub width_px: u32,
    #[prost(uint32, tag = "8")]
    pub height_px: u32,
    #[prost(uint32, tag = "9")]
    pub width_cells: u32,
    #[prost(uint32, tag = "10")]
    pub height_cells: u32,
    #[prost(uint32, tag = "11")]
    pub source_x_offset_px: u32,
    #[prost(uint32, tag = "12")]
    pub visible_width_px: u32,
    #[prost(uint32, tag = "13")]
    pub source_y_offset_px: u32,
    #[prost(uint32, tag = "14")]
    pub visible_height_px: u32,
    #[prost(int32, tag = "15")]
    pub z_index: i32,
    #[prost(int32, tag = "16")]
    pub x_offset_px: i32,
    #[prost(int32, tag = "17")]
    pub y_offset_px: i32,
    #[prost(bool, tag = "18")]
    pub preserve_aspect_ratio: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerminalFrameKind {
    Unspecified = 0,
    Snapshot = 1,
    Delta = 2,
}
impl TerminalFrameKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TERMINAL_FRAME_KIND_UNSPECIFIED",
            Self::Snapshot => "TERMINAL_FRAME_KIND_SNAPSHOT",
            Self::Delta => "TERMINAL_FRAME_KIND_DELTA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TERMINAL_FRAME_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "TERMINAL_FRAME_KIND_SNAPSHOT" => Some(Self::Snapshot),
            "TERMINAL_FRAME_KIND_DELTA" => Some(Self::Delta),
            _ => None,
        }
    }
}
