// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GraphicAssetPacketV1 {
    #[prost(uint32, tag = "1")]
    pub schema_version: u32,
    #[prost(string, tag = "2")]
    pub contract: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message_class: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub message_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub asset_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub asset_version: ::prost::alloc::string::String,
    #[prost(uint32, tag = "8")]
    pub width: u32,
    #[prost(uint32, tag = "9")]
    pub height: u32,
    #[prost(bytes = "vec", tag = "10")]
    pub rgba: ::prost::alloc::vec::Vec<u8>,
}
