name: ianvs_terminal
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  fixnum: ^1.1.1
  ianvs_pty:
    path: ../ianvs_pty
  protobuf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
