name: ianvs_terminal
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"
resolution: workspace

dependencies:
  crypto: ^3.0.7
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  ianvs_pty:
    path: ../ianvs_pty
  protobuf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
