import 'dart:convert';
import 'dart:io';

import 'package:flutterm_terminal/flutterm_terminal.dart' as terminal;

import 'platform_paths.dart';

terminal.TerminalSessionConfig applyShellIntegration(
  terminal.TerminalSessionConfig config, {
  Directory? stateDirectory,
  Map<String, String>? environment,
}) {
  if (!_isZsh(config.launch.program)) {
    return config;
  }

  final effectiveEnvironment = environment ?? Platform.environment;
  final supportDirectory =
      stateDirectory ?? Directory(defaultTerminalStateDirectoryPath());
  final zdotdir = Directory('${supportDirectory.path}/shell-integration/zsh');
  zdotdir.createSync(recursive: true);

  final home = defaultUserHomePath(environment: effectiveEnvironment);
  final originalZdotdir = _nonEmpty(effectiveEnvironment['ZDOTDIR']) ?? home;
  _writeGeneratedZshFiles(zdotdir);

  final env = <String, String>{
    ...config.launch.env,
    'FLUTTERM_SHELL_HOOKS': '1',
    'FLUTTERM_SHELL_HOOK_PROTOCOL': 'dcs-hook-v1',
    'FLUTTERM_ORIGINAL_ZDOTDIR': originalZdotdir,
    'ZDOTDIR': zdotdir.path,
  };

  return config.copyWith(launch: config.launch.copyWith(env: env));
}

String encodeShellHookDcs(Map<String, Object?> payload) {
  final json = jsonEncode(payload);
  final hex = utf8.encode(json).map(_hexByte).join();
  return '\x1bPhook;$hex\x1b\\';
}

bool _isZsh(String program) => _basename(program) == 'zsh';

String _basename(String path) {
  final normalized = path.trim();
  final slash = normalized.lastIndexOf('/');
  return slash < 0 ? normalized : normalized.substring(slash + 1);
}

String? _nonEmpty(String? value) {
  final trimmed = value?.trim();
  if (trimmed == null || trimmed.isEmpty) {
    return null;
  }
  return trimmed;
}

String _hexByte(int byte) => byte.toRadixString(16).padLeft(2, '0');

void _writeGeneratedZshFiles(Directory zdotdir) {
  File('${zdotdir.path}/.zshenv').writeAsStringSync(_zshenvContent);
  File('${zdotdir.path}/.zshrc').writeAsStringSync(_zshrcContent);
}

const _zshenvContent = r'''
# Generated by Ianvs Terminal. Do not edit.
__flutterm_generated_zdotdir="${ZDOTDIR}"
if [[ -n "${FLUTTERM_ORIGINAL_ZDOTDIR:-}" && -r "${FLUTTERM_ORIGINAL_ZDOTDIR}/.zshenv" ]]; then
  source "${FLUTTERM_ORIGINAL_ZDOTDIR}/.zshenv"
elif [[ -r "${HOME}/.zshenv" ]]; then
  source "${HOME}/.zshenv"
fi
export ZDOTDIR="${__flutterm_generated_zdotdir}"
unset __flutterm_generated_zdotdir
''';

const _zshrcContent = r'''
# Generated by Ianvs Terminal. Do not edit.
if [[ -n "${FLUTTERM_ORIGINAL_ZDOTDIR:-}" && -r "${FLUTTERM_ORIGINAL_ZDOTDIR}/.zshrc" ]]; then
  source "${FLUTTERM_ORIGINAL_ZDOTDIR}/.zshrc"
elif [[ -r "${HOME}/.zshrc" ]]; then
  source "${HOME}/.zshrc"
fi

if [[ "${FLUTTERM_SHELL_HOOKS:-}" == "1" ]]; then
  autoload -Uz add-zsh-hook
  typeset -g __FLUTTERM_SHELL_HOOK_ACTIVE=0

  __flutterm_shell_hook_hex() {
    od -An -tx1 | tr -d ' \n'
  }

  __flutterm_shell_hook_json_escape() {
    emulate -L zsh
    local value="$1"
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//$'\n'/\\n}
    value=${value//$'\r'/\\r}
    value=${value//$'\t'/\\t}
    print -rn -- "$value"
  }

  __flutterm_shell_hook_emit() {
    emulate -L zsh
    local json="$1"
    local hex="$(print -rn -- "$json" | __flutterm_shell_hook_hex)"
    print -rn -- $'\eP'"hook;${hex}"$'\e\\'
  }

  __flutterm_shell_hook_preexec() {
    emulate -L zsh
    __FLUTTERM_SHELL_HOOK_ACTIVE=1
    local command="$(__flutterm_shell_hook_json_escape "$1")"
    __flutterm_shell_hook_emit "{\"hook\":\"preexec\",\"command\":\"${command}\"}"
  }

  __flutterm_shell_hook_precmd() {
    local exit_code=$?
    emulate -L zsh
    if [[ "${__FLUTTERM_SHELL_HOOK_ACTIVE:-0}" == "1" ]]; then
      __FLUTTERM_SHELL_HOOK_ACTIVE=0
      __flutterm_shell_hook_emit "{\"hook\":\"command_finished\",\"exit_code\":${exit_code}}"
    fi
    local pwd_value="$(__flutterm_shell_hook_json_escape "$PWD")"
    __flutterm_shell_hook_emit "{\"hook\":\"precmd\",\"pwd\":\"${pwd_value}\"}"
  }

  add-zsh-hook -d preexec __flutterm_shell_hook_preexec 2>/dev/null || true
  add-zsh-hook -d precmd __flutterm_shell_hook_precmd 2>/dev/null || true
  add-zsh-hook preexec __flutterm_shell_hook_preexec
  add-zsh-hook precmd __flutterm_shell_hook_precmd
fi
''';
