import 'dart:convert';
import 'dart:io';

import 'simple_yaml.dart';

final class BenchResizeStep {
  const BenchResizeStep({required this.cols, required this.rows});

  final int cols;
  final int rows;

  Map<String, Object?> toJson() => <String, Object?>{
    'cols': cols,
    'rows': rows,
  };
}

final class BenchWorkload {
  const BenchWorkload({
    required this.name,
    required this.category,
    required this.profile,
    required this.traceBytes,
    required this.defaultCols,
    required this.defaultRows,
    required this.durationLimitSeconds,
    required this.expectedMetadata,
    this.resizeSteps = const <BenchResizeStep>[],
  });

  final String name;
  final String category;
  final String profile;
  final List<int> traceBytes;
  final int defaultCols;
  final int defaultRows;
  final int durationLimitSeconds;
  final Map<String, Object?> expectedMetadata;
  final List<BenchResizeStep> resizeSteps;

  String get traceText => utf8.decode(traceBytes);

  Map<String, Object?> toWorkloadYamlMap() {
    return <String, Object?>{
      'name': name,
      'type': resizeSteps.isEmpty
          ? 'deterministic_trace'
          : 'deterministic_trace_with_resize',
      'cols': defaultCols,
      'rows': defaultRows,
      'duration_limit_seconds': durationLimitSeconds,
      'expected': expectedMetadata,
      'metrics': <String>[
        'coalescing_ratio',
        'rows_emitted',
        'frame_build_micros',
        'final_viewport_hash',
      ],
    };
  }

  void writeToDirectory(Directory directory) {
    directory.createSync(recursive: true);
    File('${directory.path}/trace.stdout.bin').writeAsBytesSync(traceBytes);
    File('${directory.path}/expected_metadata.json').writeAsStringSync(
      const JsonEncoder.withIndent('  ').convert(expectedMetadata),
    );
    File(
      '${directory.path}/workload.yaml',
    ).writeAsStringSync(SimpleYaml.encodeMap(toWorkloadYamlMap()));
    File('${directory.path}/README.md').writeAsStringSync('''
# $name

Deterministic benchmark workload generated by `tools/bench`.

- category: `$category`
- profile: `$profile`
- viewport: `${defaultCols}x$defaultRows`
''');
  }
}

final class BenchWorkloadCatalog {
  BenchWorkload resolve(String name) {
    final parts = name.split('.');
    if (parts.length != 2) {
      throw FormatException('Invalid workload name: $name');
    }
    final category = parts[0];
    final profile = parts[1];
    return switch (category) {
      'idle' => _idle(profile),
      'burst_stdout' => _burstStdout(profile),
      'scrollback_heavy' => _scrollbackHeavy(profile),
      'resize_churn' => _resizeChurn(profile),
      _ => throw FormatException('Unknown workload category: $category'),
    };
  }

  Iterable<String> get mvpWorkloadNames sync* {
    yield 'idle.quiet';
    yield 'burst_stdout.seq_1000';
    yield 'burst_stdout.seq_100k';
    yield 'burst_stdout.repeated_payload_100k';
    yield 'scrollback_heavy.lines_1000';
    yield 'scrollback_heavy.lines_100k';
    yield 'scrollback_heavy.lines_200k';
    yield 'resize_churn.tiny';
    yield 'resize_churn.basic';
    yield 'resize_churn.extended';
  }
}

BenchWorkload _idle(String profile) {
  if (profile != 'quiet') {
    throw FormatException('Unknown idle profile: $profile');
  }
  return const BenchWorkload(
    name: 'idle.quiet',
    category: 'idle',
    profile: 'quiet',
    traceBytes: <int>[],
    defaultCols: 120,
    defaultRows: 40,
    durationLimitSeconds: 10,
    expectedMetadata: <String, Object?>{
      'requires_hash_match': true,
      'expects_idle_resource_baseline': true,
    },
  );
}

BenchWorkload _burstStdout(String profile) {
  final lineCount = switch (profile) {
    'seq_1000' => 1000,
    'seq_100k' => 100000,
    'seq_1m' => 1000000,
    'repeated_payload_100k' => 100000,
    _ => throw FormatException('Unknown burst_stdout profile: $profile'),
  };
  final buffer = StringBuffer();
  if (profile == 'repeated_payload_100k') {
    for (var i = 1; i <= lineCount; i += 1) {
      buffer.writeln(
        'payload ${i.toString().padLeft(6, '0')} | '
        '0123456789 abcdefghijklmnopqrstuvwxyz',
      );
    }
  } else {
    for (var i = 1; i <= lineCount; i += 1) {
      buffer.writeln(i);
    }
  }
  return BenchWorkload(
    name: 'burst_stdout.$profile',
    category: 'burst_stdout',
    profile: profile,
    traceBytes: utf8.encode(buffer.toString()),
    defaultCols: 120,
    defaultRows: 40,
    durationLimitSeconds: profile == 'seq_1000' ? 10 : 30,
    expectedMetadata: const <String, Object?>{
      'requires_hash_match': true,
      'max_snapshot_ratio': 0.20,
    },
  );
}

BenchWorkload _scrollbackHeavy(String profile) {
  final lineCount = switch (profile) {
    'lines_1000' => 1000,
    'lines_100k' => 100000,
    'lines_200k' => 200000,
    _ => throw FormatException('Unknown scrollback_heavy profile: $profile'),
  };
  final buffer = StringBuffer();
  for (var i = 1; i <= lineCount; i += 1) {
    buffer.writeln(
      'line ${i.toString().padLeft(8, '0')} | scroll benchmark payload',
    );
  }
  return BenchWorkload(
    name: 'scrollback_heavy.$profile',
    category: 'scrollback_heavy',
    profile: profile,
    traceBytes: utf8.encode(buffer.toString()),
    defaultCols: 120,
    defaultRows: 40,
    durationLimitSeconds: profile == 'lines_1000' ? 10 : 30,
    expectedMetadata: const <String, Object?>{
      'requires_hash_match': true,
      'expects_viewport_row_shift': true,
    },
  );
}

BenchWorkload _resizeChurn(String profile) {
  final repeat = switch (profile) {
    'tiny' => 10,
    'basic' => 100,
    'extended' => 250,
    _ => throw FormatException('Unknown resize_churn profile: $profile'),
  };
  const basicSteps = <BenchResizeStep>[
    BenchResizeStep(cols: 120, rows: 40),
    BenchResizeStep(cols: 80, rows: 24),
    BenchResizeStep(cols: 160, rows: 50),
    BenchResizeStep(cols: 100, rows: 30),
  ];
  final steps = switch (profile) {
    'tiny' => basicSteps.take(2).toList(growable: false),
    'basic' => basicSteps,
    'extended' => <BenchResizeStep>[...basicSteps, ...basicSteps.reversed],
    _ => basicSteps,
  };
  final buffer = StringBuffer();
  for (var i = 1; i <= repeat * 20; i += 1) {
    buffer.writeln('resize churn line ${i.toString().padLeft(5, '0')}');
  }
  return BenchWorkload(
    name: 'resize_churn.$profile',
    category: 'resize_churn',
    profile: profile,
    traceBytes: utf8.encode(buffer.toString()),
    defaultCols: steps.first.cols,
    defaultRows: steps.first.rows,
    durationLimitSeconds: profile == 'tiny' ? 10 : 30,
    resizeSteps: steps,
    expectedMetadata: const <String, Object?>{
      'requires_hash_match': true,
      'expects_resize_fallback': true,
    },
  );
}
