name: ianvs_pty
publish_to: none

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.2.0
  hooks: ^1.0.0
  protobuf: ^6.0.0

dev_dependencies:
  test: ^1.26.0
