name: flutterm_terminal
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutterm_pty:
    path: ../flutterm_pty

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
