import 'dart:typed_data';

/// Minimal output boundary used by terminal input handling.
///
/// Keeping this capability separate from the runtime controller prevents the
/// terminal widget/input layer from depending on session orchestration.
abstract interface class TerminalInputSink {
  void sendInput(String sessionId, Uint8List bytes);
}

/// Optional capability for reports generated by the terminal rather than a
/// user's keyboard, pointer, or paste. Input observers can preserve automation
/// when the terminal reports focus or replies to an application query.
abstract interface class TerminalProtocolInputSink
    implements TerminalInputSink {
  void sendProtocolInput(String sessionId, Uint8List bytes);
}
